### PR TITLE
Update for V8

### PR DESCRIPTION
**Pull request by papadkostas**
Updated to latest version.
https://youtu.be/o1ABinuvlVU
Please let me know if you want a steady video with tripod if this board is going to be officially certified.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thank you very much!

In v8 the [touchpad's read_cb](https://github.com/lvgl/lv_port_stm32f769_disco/blob/master/hal_stm_lvgl/touchpad/touchpad.c#L27) should return void.

Could you make `lv_demo_widget`'s the default? The music demo is not scaled perfectly to this screen size and orientation by default plus the widgets demo is more general and shows more about what LVGL is.

**Comment by papadkostas** [comment]
Done.
Indeed it does not scale good. 
I tried to set the following but the resolution is very high and gets very laggy.
```
# define LV_DEMO_MUSIC_LANDSCAPE 1
# define LV_DEMO_MUSIC_LARGE     1
```

**Comment by kisvegabor** [comment]
Thanks, merging. As you mentioned, could you make a video about the widget demo? 

800x480 is an unfortunate resolution for the music player demo. Too large for the small version and too small for the large version.

**Comment by papadkostas** [comment]
Of course! I will do it soon 😃

**Comment by papadkostas** [comment]
Sorry for the delay, I've been trying to make a better one with tripod but I gave up.
My DSLR got no HDR and metering on the display makes everything dark.
I'll give it a shot another day for something better so you can upload it on youtube.
https://www.youtube.com/watch?v=R7hxZIechBc

**Comment by kisvegabor** [comment]
We use many lamps to light the background but it's quite cumbersome. 

Feel free to upload it to your profile and I'll add it to LVGL's [Community videos](https://www.youtube.com/watch?v=iG1S-sk82sQ&list=PLJITc6klxx8_5gYAdV2eJqdN9qnAJ_CN9) playlist.

**Pull request merged**
